# Executes once a week (Sunday) to fetch updates from all manifests
on:
  workflow_dispatch:
  schedule:
    # At 04:37 on every other day.
    - cron: '37 4 */2 * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Update Manifests
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
