# This is a basic workflow that is manually triggered

name: Manual Excavator

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: shovel-org/GithubActions@main
      env:
        GITH_EMAIL: 62065280+jack-mil@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
